events {
    worker_connections 1024;
}

http {
    
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

    
    upstream api_v1 {
        server api-v1:8000;
    }

    upstream api_v2 {
        server api-v2:8000;
    }

    
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name localhost;

        
        ssl_certificate /etc/nginx/certs/nginx.crt;
        ssl_certificate_key /etc/nginx/certs/nginx.key;

        
        auth_basic "Restricted Access";
        auth_basic_user_file /etc/nginx/.htpasswd;

        location /predict {
            
            limit_req zone=api_limit burst=5 nodelay;

           
            set $api_service "api_v1";
            if ($http_x_experiment_group = "debug") {
                set $api_service "api_v2";
            }

            proxy_pass http://$api_service;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /nginx_status {
        stub_status on; # Active le module stub_status
        access_log off; # Do not log access to this endpoint
        allow 127.0.0.1; # Allow access only from localhost (export it)
        allow 172.21.0.0/16; # Or from the Docker network
        deny all; # Blocks all other access
        }
    }
}

